#!/bin/sh
#SBATCH -p v2_all
#SBATCH -J ccs
module load mpi/intel/18.0.2
VASP_PATH=/public1/home/pg2059/apps/vasp.5.4.4/bin
cd $SLURM_SUBMIT_DIR
srun -n 40 -N 2 /public1/home/pg2059/opt/VASP/vasp.5.4.4-optcell-vtst/bin/vasp_std
